apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-benchmark
  labels:
    app: redis-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-benchmark
  template:
    metadata:
      labels:
        app: redis-benchmark
        kubmin.ksctl.com/workload: "true"
      annotations:
        kubmin.ksctl.com/measure: |
          version: 1
          containers:
            cache:
              unit: container-hour
    spec:
      containers:
        - name: cache
          image: redis:8.4.0
          ports:
            - containerPort: 6379
              name: redis
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "250Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-benchmark
spec:
  selector:
    app: redis-benchmark
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  type: ClusterIP
